<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'index' => [[], ['_controller' => 'App\\Controller\\DefaultController::number'], [], [['text', '/']], [], [], []],
    'ebook_reader' => [['name'], ['_controller' => 'App\\Controller\\DefaultController::ebookReader'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/ebookReader']], [], [], []],
    'App\Controller\DefaultController::number' => [[], ['_controller' => 'App\\Controller\\DefaultController::number'], [], [['text', '/']], [], [], []],
    'App\Controller\DefaultController::ebookReader' => [['name'], ['_controller' => 'App\\Controller\\DefaultController::ebookReader'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/ebookReader']], [], [], []],
];
