<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1zDqmz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1zDqmz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX1zDqmz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX1zDqmz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX1zDqmz\App_KernelDevDebugContainer([
    'container.build_hash' => 'X1zDqmz',
    'container.build_id' => '5d1982b3',
    'container.build_time' => 1746429653,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1zDqmz');
